- nexus_motion_planner/CMakeLists.txt
- nexus_motion_planner/launch/demo_planner_server.launch.py
- nexus_motion_planner/src/motion_planner_server.cpp
The `nexus_motion_planner` spins an internal `rclcpp::Node::SharedPtr` since `moveit's` `move_group_interface` API does is not compatible with a `LifecycleNode`.  Looking at the implementation, we were trying to declare some of the move_group related parameters in the LifecycleNode and then "forward" the declaration to the internal node. However there is no need to do this since we can just pass the same `NodeOptions` to the internal node which will also pass the `arguments` to the ROS 2 node which the move_group_interface will rely on to declare relevant parameters. 
Without this fix, I was seeing a couple of warning in the terminal from not declaring certain essential moveit parameters as arguments were missing. But now by passing the same options, the internal node has access to the …
> Pass same NodeOptions to planner's internal node

- nexus_capabilities/src/capabilities/plan_motion.cpp
- nexus_capabilities/src/capabilities/plan_motion.hpp
- nexus_motion_planner/src/motion_planner_server.cpp
- nexus_msgs/nexus_motion_planner_msgs/srv/GetMotionPlan.srv
- nexus_tree_nodes.xml
Builds on top of: https://github.com/osrf/nexus/pull/28
Adds the ability to force a GetMotionPlan service request to use motion cache mode ExecuteReadOnly regardless of the server's cache mode, on a per request basis.
> Add force_cache_mode_execute_read_only

- nexus_capabilities/src/capabilities/plan_motion.cpp
- nexus_capabilities/src/capabilities/plan_motion.hpp
- nexus_motion_planner/CMakeLists.txt
- nexus_motion_planner/package.xml
- nexus_motion_planner/src/motion_plan_cache.cpp
- nexus_motion_planner/src/motion_plan_cache.hpp
- nexus_motion_planner/src/motion_planner_server.cpp
- nexus_motion_planner/src/motion_planner_server.hpp
- nexus_motion_planner/src/test_motion_plan_cache.cpp
- nexus_motion_planner/test/test_motion_plan_cache.py
- nexus_msgs/nexus_motion_planner_msgs/srv/GetMotionPlan.srv
- nexus_tree_nodes.xml
This PR addresses code review comments across the following PRs:
- https://github.com/osrf/nexus/pull/16
- https://github.com/osrf/nexus/pull/18
It's done as a separate PR so the pending PRs don't need to be constantly rebased (and changes duplicated.)
The git history now looks like:
```
d1847ba (HEAD -> ch3/plan-cache-code-review-fixes, origin/ch3/plan-cache-code-review-fixes)
...
b2cda90 (origin/ch3/cartesian-plan-cache, ch3/cartesian-plan-cache) Fix move bug
...
ca0f123 (origin/ch3/motion-plan-cache, ch3/motion-plan-cache) Remove internal cache node
...
dcede0e (tag: 0.1.1, origin/main, origin/HEAD) Bump versions to 0.1.1 (#25)
```
- Remove usage of query appending macro
- Default to warehouse_ros plugin if parameter is not set
- Return and check cache init result
- Add explanatory …
> Plan cache code review fixes (sans unit tests)

- nexus_capabilities/src/capabilities/plan_motion.cpp
- nexus_capabilities/src/capabilities/plan_motion.hpp
- nexus_motion_planner/CMakeLists.txt
- nexus_motion_planner/package.xml
- nexus_motion_planner/src/motion_plan_cache.cpp
- nexus_motion_planner/src/motion_plan_cache.hpp
- nexus_motion_planner/src/motion_planner_server.cpp
- nexus_motion_planner/src/motion_planner_server.hpp
- nexus_motion_planner/src/test_motion_plan_cache.cpp
- nexus_motion_planner/test/test_motion_plan_cache.py
- nexus_msgs/nexus_motion_planner_msgs/srv/GetMotionPlan.srv
- nexus_tree_nodes.xml
```
*   This cache does NOT support collision detection!
*   Plans will be put into and fetched from the cache IGNORING collision.
*   If your planning scene is expected to change between cache lookups, do NOT
*   use this cache, fetched plans are likely to result in collision then.
*
*   To handle collisions this class will need to hash the planning scene world
*   msg (after zeroing out std_msgs/Header timestamps and sequences) and do an
*   appropriate lookup. (very out of scope)
```
This PR builds on top of:
- https://github.com/osrf/nexus/pull/16
It implements and uses the plan cache for cartesian plans!
Cached plans appear in the `move_group_cartesian_plan_cache` collection in the db:
> Implement cartesian plan cache

- .github/workflows/nexus_integration_tests.yaml
- nexus_motion_planner/CMakeLists.txt
- nexus_motion_planner/config/planner_params.yaml
- nexus_motion_planner/config/planner_params_with_cache.yaml
- nexus_motion_planner/package.xml
- nexus_motion_planner/test/test_request_with_cache.test.py
Builds on top of:
- https://github.com/osrf/nexus/pull/16
I uncommented the old launch test, and discovered it was passing.
Then I tried adding a test for the motion plan cache, and had it fail because we need access to the robot joint state.
Turns out the old tests weren't loading a ros2_control controller, so I fixed it (maybe that's what broke in the first place?)
After building, test with:
```
clear && colcon test --packages-select nexus_motion_planner --event-handlers=console_direct+
```
> Fix and add motion planner server tests

- .github/workflows/nexus_integration_tests.yaml
- nexus_capabilities/src/capabilities/plan_motion.cpp
- nexus_capabilities/src/capabilities/plan_motion.hpp
- nexus_motion_planner/CMakeLists.txt
- nexus_motion_planner/config/planner_params.yaml
- nexus_motion_planner/config/planner_params_with_cache.yaml
- nexus_motion_planner/package.xml
- nexus_motion_planner/src/main.cpp
- nexus_motion_planner/src/motion_plan_cache.cpp
- nexus_motion_planner/src/motion_plan_cache.hpp
- nexus_motion_planner/src/motion_planner_server.cpp
- nexus_motion_planner/src/motion_planner_server.hpp
- nexus_motion_planner/src/test_motion_plan_cache.cpp
- nexus_motion_planner/test/test_motion_plan_cache.py
- nexus_motion_planner/test/test_request_with_cache.test.py
- nexus_msgs/nexus_motion_planner_msgs/srv/GetMotionPlan.srv
- nexus_tree_nodes.xml
```
*   This cache does NOT support collision detection!
*   Plans will be put into and fetched from the cache IGNORING collision.
*   If your planning scene is expected to change between cache lookups, do NOT
*   use this cache, fetched plans are likely to result in collision then.
*
*   To handle collisions this class will need to hash the planning scene world
*   msg (after zeroing out std_msgs/Header timestamps and sequences) and do an
*   appropriate lookup. (very out of scope)
```
This PR adds a `MotionPlanCache` class that wraps a `warehouse_ros` database interface.
It is then incorporated into the motion_planning_server.
Features:
- Put and fetch `RobotTrajectory` plans keyed by `MotionPlanRequest` message values
- This includes ALL joint, position, and orientation constraints!
- …
> Implement motion plan cache

- README.md
- nexus_motion_planner/src/motion_planner_server.cpp
- nexus_tree_nodes.xml
Follow up to #16.
Enforce plan to be fetched if request containts `force_cache_mode_execute_read_only=true`. This logic already exists for the cartesian requests.
> Return error if not plan was fetched for non-cartesian requests

- .github/workflows/nexus_integration_tests.yaml
- nexus_calibration/CHANGELOG.rst
- nexus_calibration/CMakeLists.txt
- nexus_calibration/README.md
- nexus_calibration/config/sample_config.yaml
- nexus_calibration/package.xml
- nexus_calibration/src/calibration_node.cpp
- nexus_calibration/src/calibration_node.hpp
- nexus_calibration/test/nexus_calibration.launch.py
- nexus_calibration/test/test_config.yaml
- nexus_calibration/test/test_world.world
This package provides a ROS 2 Lifecyle node, `nexus_calibration_node`, that connects to a [VRPN](https://vrpn.github.io/) server and builds a cache of rigid body poses in a local `TF2` buffer.
These rigid bodies could represent calibration links (or reference links) on components within a workcell.
The poses of these links can then be queried via a ROS 2 service call over the `nexus::endpoints::ExtrinsicCalibrationService` endpoint.
```bash
cd nexus_calibration/
ros2 launch test/nexus_calibration.launch.py
``
Then to retrieve poses of components wrt to the `robot_calibration_link`, ie a reference frame on the robot's `base_link`,
```bash
ros2 service call /workcell_1/calibrate_extrinsics nexus_calibration_msgs/src/CalibrateExtrinsics '{frame_id: robot_calibration_link}'
```
Requires #33
> nexus_calibration

- nexus_integration_tests/config/zenoh/nexus_network_config.yaml
- nexus_integration_tests/launch/zenoh_bridge.launch.py
- nexus_network_configuration/nexus_network_configuration/nexus_network_configuration.py
- nexus_network_configuration/schemas/nexus_network_schema.json
- nexus_zenoh_bridge_dds_vendor/CMakeLists.txt
Closes #17.
This seems to work but required a fair bit of changes in the `nexus_network_configuration` package, so we should probably rethink what that package does and how.
Specifically, it had a builtin support for generating configs from redf, but it actually didn't and just used hardcoded endpoints [here](https://github.com/osrf/nexus/blob/0741639171413cd077fb7862b85396210cc35bcb/nexus_integration_tests/config/zenoh/nexus_network_config.yaml#L10).
Furthermore, while with the `dds` plugin we can just specify endpoints as strings, the `ros2dds` plugin requires us to clearly say whether each substring is a publisher, subscriber, service server, service client, action server or action client.
The way I approached it in this PR is the same as the previous PR, [updating the config …
> Migrate to ros2dds bridge

- LICENSE
Per #44, this license file hadn't been added yet.
This PR fixes that by adding the Apache-2.0 license, which is in line with other OSRF projects. :-)
> Adding Apache-2.0 license

- nexus_lifecycle_manager/include/nexus_lifecycle_manager/lifecycle_manager.hpp
This PR works toward https://github.com/osrf/nexus/issues/48 by fixing corner cases with workcells bringup / bringdown.
The logic in the lifecycle manager was flawed, specifically in the [branch](https://github.com/osrf/nexus/blob/a0eff3c52dcf63ad499da0f88daa2df9bceed220/nexus_lifecycle_manager/include/nexus_lifecycle_manager/lifecycle_manager.hpp#L373-L403) where nodes already exist and a new one is added.
Two main issues are fixed by this PR.
If Nexus has a single workcell, that workcell is brought down without proper cleanup (i.e. it suddenly crashes) then it's readded, we will go into the branch I linked above. However, when we try to get the target state https://github.com/osrf/nexus/blob/a0eff3c52dcf63ad499da0f88daa2df9bceed220/nexus_lifecycle_manager/include/nexus_lifecycle_manager/ …
> Fix registration logic in lifecycle manager

- nexus_common/CMakeLists.txt
- nexus_common/include/nexus_common/task_remapper.hpp
- nexus_common/src/task_remapper.cpp
- nexus_common/src/task_remapper_test.cpp
- nexus_system_orchestrator/src/context.hpp
- nexus_system_orchestrator/src/execute_task.cpp
- nexus_system_orchestrator/src/system_orchestrator.cpp
- nexus_system_orchestrator/src/system_orchestrator.hpp
- nexus_workcell_orchestrator/src/task_parser.cpp
- nexus_workcell_orchestrator/src/task_parser.hpp
- nexus_workcell_orchestrator/src/workcell_orchestrator.cpp
- nexus_workcell_orchestrator/src/workcell_orchestrator.hpp
This PR refactors the task remapping capability in `nexus_system_orchestrator` (which was fully fledged) and the one in `nexus_workcell_orchestrator` (that was actually unimplemented) into a common `TaskRemapper` class.
This class has basic wildcard support, if it finds such a remapping:
```
pick_and_place: ["*"],
```
It will override every other defined remap and just remap every single task to the requested `pick_and_place`.
I added a set of unit tests to show how the functionality works and now both system and workcell orchestrator share the same codebase for task remapping.
In the future we can consider more complex behaviors (i.e. proper wildcard support)
> Introduce a common TaskRemapper with wildcard support

- nexus_calibration/CMakeLists.txt
- nexus_calibration/package.xml
- nexus_capabilities/CMakeLists.txt
- nexus_capabilities/package.xml
- nexus_common/CMakeLists.txt
- nexus_common/package.xml
- nexus_demos/CMakeLists.txt
- nexus_demos/package.xml
- nexus_endpoints/CMakeLists.txt
- nexus_endpoints/package.xml
- nexus_gazebo/CMakeLists.txt
- nexus_gazebo/package.xml
- nexus_lifecycle_manager/CMakeLists.txt
- nexus_lifecycle_manager/package.xml
- nexus_motion_planner/CMakeLists.txt
- nexus_motion_planner/package.xml
- nexus_robot_controller/CMakeLists.txt
- nexus_robot_controller/package.xml
- nexus_rviz_plugins/CMakeLists.txt
- nexus_rviz_plugins/package.xml
- nexus_system_orchestrator/CMakeLists.txt
- nexus_system_orchestrator/package.xml
- nexus_transporter/CMakeLists.txt
- nexus_transporter/package.xml
- nexus_workcell_orchestrator/CMakeLists.txt
- nexus_workcell_orchestrator/package.xml
Was running some scenarios and saw crashes with workcell orchestrator. Adding [backwards_ros](https://github.com/pal-robotics/backward_ros) to automatically dump stack traces for easier debugging.
> Inject backward_ros

- nexus_common/include/nexus_common/logging.hpp
- nexus_demos/launch/inter_workcell.launch.py
- nexus_demos/launch/workcell.launch.py
- nexus_system_orchestrator/src/system_orchestrator.cpp
- nexus_workcell_orchestrator/src/workcell_orchestrator.cpp
Stopgap solution for #59.
This PR updates the `BTLogging` class to accept a list of nodes that that we want to blocklist for logging.
Also updates system and workcell orchestrators to get these node names via a `bt_logging_blocklist` param. The launch file s are updated set this param to blocklist `IsPauseTriggered` which prevents terminal spam when running a process.
> Allow certain BT nodes to be blocklisted for logging

- nexus_common/include/nexus_common/models/metadata.hpp
- nexus_common/include/nexus_common/models/work_order.hpp
- nexus_common/src/models/work_order_test.cpp
- nexus_demos/config/pick_and_place.json
- nexus_demos/config/pick_from_conveyor.json
- nexus_demos/config/place_on_conveyor.json
- nexus_system_orchestrator/src/system_orchestrator.cpp
This PR
- Gets rid of `Item` as a required field in the work order. This is replaced by `MetaData` which is optional in the work order. Users can directly access the yaml contents.
- Gets rid of `name` inside `Step` as it was redundant.
- Adds a getter for `process_parameters` in `Step` to return a YAML node of parameters. Downstream skills should have access to these parameters via `Task.data ` in the [context during configuration](https://github.com/osrf/nexus/blob/eb61acfab2cf44235ff132507a803e968ae92f9b/nexus_capabilities/include/nexus_capabilities/capability.hpp#L59)
> Update default  WorkOrder model

- .github/workflows/nexus_integration_tests.yaml
- .github/workflows/nexus_unit_tests.yaml
- .gitignore
- nexus_common/CMakeLists.txt
- nexus_common/include/nexus_common/action_client_bt_node.hpp
- nexus_common/include/nexus_common/batch_service_call.hpp
- nexus_common/include/nexus_common/logging.hpp
- nexus_common/include/nexus_common/models/item.hpp
- nexus_common/include/nexus_common/models/work_order.hpp
- nexus_common/package.xml
- nexus_common/src/action_client_bt_node_test.cpp
- nexus_common/src/models/item_test.cpp
- nexus_common/src/models/work_order_test.cpp
- nexus_common/src/node_utils.cpp
- nexus_demos/CMakeLists.txt
- nexus_demos/config/pick_and_place.json
- nexus_demos/config/pick_from_conveyor.json
- nexus_demos/config/place_on_conveyor.json
- nexus_motion_planner/package.xml
- nexus_system_orchestrator/src/system_orchestrator.cpp
- nexus_transporter/test/test_Itinerary.cpp
This is will be one of the key concepts needed to set individual transportation steps for each work order step. 
* added `Item`, which has a guid and metadata, added test
* added input and output items for steps (this will be used to inform dispensers/ingesters
* tidied up CI, added separate unit test workflow (that won't build bridges)
In the future, when work orders need to be generated, the inputs and outputs can also help inform pre and post conditions of each step.  
I did some linting fixes too, but only on the packages that I touched with this PR. Will set up proper linting in a subsequent PR for the entire project.
> Input and output items for steps

- nexus_common/include/nexus_common/action_client_bt_node.hpp
- nexus_common/include/nexus_common/service_client_bt_node.hpp
A minor improvement to allow users to override a cancellation callback that will be called when a BT node in `nexus_common` is halted.
> Cancel callbacks for BT nodes in nexus_common

- nexus_capabilities/src/capabilities/rmf_request.cpp
- nexus_capabilities/src/capabilities/rmf_request.hpp
- nexus_capabilities/src/capabilities/rmf_request_capability.cpp
- nexus_demos/CMakeLists.txt
- nexus_demos/launch/rmf_transporter.launch.xml
- nexus_demos/package.xml
- nexus_demos/src/rmf_task_canceller.cpp
- nexus_demos/src/rmf_task_canceller.hpp
This PR adds a `rmf_task_canceller` node that properly cancels RMF tasks when a workcell's task fails or is aborted. It does this by subscribing to the `/work_order_states` and keeps track of those WorkOrders that were cancelled. It also subscribes to `/<rmf_transporter_name>/workcell_state` to track the current task being done by the RMF Transporter. If this task matches one that has been cancelled AND DispenserRequest messages for this task are also being published, the `rmf_task_canceller` node, publishes a FAILED `DispenseResult` message and cancels the RMF task via `/task_api_requests`.
To make this work without hardcoding anything in the `rmf_task_canceller`, I updated the `rmf_request.DispatchRequest` BT node to update the current tasks's `task_id` field to match the `rmf_task_id` …
> Add rmf_task_canceller node

- nexus_capabilities/src/capabilities/rmf_request.cpp
- nexus_capabilities/src/capabilities/rmf_request.hpp
- nexus_capabilities/src/capabilities/rmf_request_capability.cpp
- nexus_demos/src/rmf_task_canceller.cpp
This PR reverts the logic introduced in #94 where the `DispatchReqeust` skill overwrites the `task_id` for the workcell. 
Turns out overwriting the `task_id` in the workcell prevents it from receiving [signals](https://github.com/osrf/nexus/blob/main/nexus_system_orchestrator/src/send_signal.cpp#L47-L48) from the system orchestrator 😅 
I removed the  `if (msg->request_guid != rmf_workcell_state_->task_id)` check in the `rmf_task_canceller` node as this was just an extra safety check. I've tested functionality locally and things work as expected.
> Do not overwrite task id in DispatchRequest

- .github/rmf/Dockerfile
- .github/workflows/build-images.yaml
With the ongoing development and integration of the RMF transporter #104 and #106 , we will need newer RMF features unreleased into jazzy. This workflow will allow us to manually trigger image builds that will have RMF source built
> Build basic RMF image, to be optionally used for CI

- .github/workflows/nexus_integration_tests.yaml
Do you know why CI has been flaky for ages?
Because specifying `--cmake-args` after the mixin overwrote the `release` mixin and we were building in debug mode.
There.
> Remove ccache from CI

- nexus_demos/launch/inter_workcell.launch.py
- nexus_transporter/src/transporters/mock_transporter.cpp
Adding conveyor mode, which lets the mock transporter start from the first destination immediately
https://github.com/user-attachments/assets/84b4f4c5-3166-4a60-a724-d26bbf98fa43
> Conveyor mode for mock transporter

- nexus_msgs/nexus_orchestrator_msgs/msg/TaskState.msg
- nexus_system_orchestrator/src/system_orchestrator.cpp
- nexus_workcell_orchestrator/src/workcell_orchestrator.cpp
* support multiple messages and error messages within `TaskState`
* system orchestrator to log messages arising from `WorkcellRequest`
We follow [OSRA's policy on GenAI tools](https://github.com/openrobotics/osrf-policies-and-procedures/blob/main/OSRF%20Policy%20on%20the%20Use%20of%20Generative%20Tools%20(%E2%80%9CGenerative%20AI%E2%80%9D)%20in%20Contributions.md)
Generated-by:
> Logging info and error messages coming from workcell orchestrators
